export const BLOCKCHAIN_EVENTS_TYPES = Object.freeze({
  councilElection: 'council-election',
  councilMotion: 'council-motion',
  democracyDispatch: 'democracy-dispatch',
  democracyLaunch: 'democracy-launch',
  parachainAuction: 'parachain-auction',
  parachainLease: 'parachain-lease',
  referendumDispatch: 'referendum-dispatch',
  referendumVote: 'referendum-vote',
  scheduler: 'scheduler',
  stakingEpoch: 'staking-epoch',
  stakingEra: 'staking-era',
  stakingSlash: 'staking-slash',
  treasurySpend: 'treasury-spend',
  societyChallenge: 'society-challenge',
  societyRotate: 'society-rotate',
})
