fragment fragTokenTransfer on TokenTransfer {
  amount
  blockNumber
  fromAddressHash
  id
  logIndex
  toAddressHash
  tokenContractAddressHash
  tokenId
  transactionHash,
  timestamp

  amount,
  tokenId,
  token {
    symbol,
    type
  }
}
