fragment fragTransaction on Transaction {
  blockNumber
  createdContractAddressHash
  cumulativeGasUsed
  fromAddressHash
  gasUsed
  gas
  gasPrice
  hash
  id
  index
  input
  nonce
  status
  toAddressHash
  timestamp
  type
  value
}
