#import "../fragments/fragTransaction.gql"
#import "../fragments/fragAddress.gql"
query getAddress(
  $hash: AddressHash!,
  $transactionAfter: String, 
  $transactionBefore: String,
  $transactionCount: Int,
  $transactionFirst: Int,
  $transactionLast: Int,
  ) {
  address(hash: $hash) {
    ...fragAddress

    transactions(
      after: $transactionAfter,
      before: $transactionBefore,
      count: $transactionCount,
      first: $transactionFirst,
      last: $transactionLast
    ) { 
      edges {
        node {
          ...fragTransaction
        }
      }
     }
  },
}
