#import "../fragments/fragTransaction.gql"
#import "../fragments/fragPageInfo.gql"

query getAddress(
  $hash: AddressHash!,
  $transactionAfter: String, 
  $transactionBefore: String,
  $transactionFirst: Int,
  $transactionLast: Int,
  ) {
  address(hash: $hash) {
    transactions(
      after: $transactionAfter,
      before: $transactionBefore,
      first: $transactionFirst,
      last: $transactionLast
    ) { 
      edges {
        node {
          ...fragTransaction
        }
      }
      pageInfo {
        ...fragPageInfo,
      }
     }
  },
}
